const SUPABASE_URL='https://axudbwobzmmrqpdnbamp.supabase.co';const SUPABASE_KEY='sb_publishable_JHJBoonYn5HFxERyv-RWKA_oKpYsV7W';const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function isAdmin(user){if(!user)return false;const {data,error}=await db.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();return !error&&!!data}
async function showSession(){const {data:{session}}=await db.auth.getSession();if(session&&await isAdmin(session.user)){ $('#loginView').hidden=true;$('#dashboardView').hidden=false;await Promise.all([loadRequests(),loadVolunteers(),loadGallery(),loadPayments(),loadUsers(),loadCourses(),loadEvents(),loadEventRequests()]);}else{$('#loginView').hidden=false;$('#dashboardView').hidden=true;if(session)await db.auth.signOut();}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('#loginStatus');st.textContent='Accesso…';const {data,error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error||!await isAdmin(data.user)){if(data.user)await db.auth.signOut();st.textContent='Accesso non autorizzato.';st.className='form-status is-error';return}st.textContent='';showSession()});$('#logoutBtn').addEventListener('click',async()=>{await db.auth.signOut();location.reload()});
document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tabs button,.admin-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
const labels={informazioni:'Informazioni',volontario:'Volontario',custode_locale:'Custode locale',custode_regionale:'Custode regionale',richiesta_casetta:'Richiesta casetta',adesione_gratuita:'Adesione gratuita',sostenitore:'Sostenitore',partner:'Partner',sponsor:'Sponsor',collaboratore:'Collaboratore'};
const volunteerTypes=['custode_regionale','custode_locale','volontario','collaboratore'];
function showDetail(title,message){$('#detailTitle').textContent=title||'Dettaglio';$('#detailBody').textContent=message||'Nessun messaggio.';$('#detailModal').hidden=false}
$('#detailClose').onclick=()=>$('#detailModal').hidden=true;
$('#detailModal').addEventListener('click',e=>{if(e.target.id==='detailModal')e.currentTarget.hidden=true});

async function loadRequests(){const el=$('#requestsList');el.innerHTML='<p>Caricamento…</p>';const {data,error}=await db.from('richieste').select('*').not('tipo','in','(custode_regionale,custode_locale,volontario,collaboratore)').order('created_at',{ascending:false});if(error){el.innerHTML='<p>Impossibile caricare le richieste.</p>';return}$('#ovRequests').textContent=data.filter(r=>!['completata','archiviata'].includes(r.stato)).length;el.innerHTML=data.length?data.map(r=>`<article class="admin-row"><div><span class="admin-chip">${esc(labels[r.tipo]||r.tipo)}</span><h3>${esc([r.nome,r.cognome].filter(Boolean).join(' ')||r.email||'Richiesta')}</h3><p>${esc(r.email||'')}${r.telefono?' · '+esc(r.telefono):''}</p><p>${esc(r.oggetto||'')}</p><small>${new Date(r.created_at).toLocaleString('it-IT')}</small></div><div><select data-request-status="${r.id}">${['nuova','contattato','in_lavorazione','completata','archiviata'].map(x=>`<option ${x===r.stato?'selected':''} value="${x}">${x.replace('_',' ')}</option>`).join('')}</select><button class="admin-detail" data-message="${encodeURIComponent(r.messaggio||'')}">Leggi</button></div></article>`).join(''):'<p>Nessuna richiesta.</p>';document.querySelectorAll('[data-request-status]').forEach(s=>s.onchange=()=>db.from('richieste').update({stato:s.value}).eq('id',s.dataset.requestStatus));document.querySelectorAll('.admin-detail').forEach(b=>b.onclick=()=>showDetail('Dettaglio richiesta',decodeURIComponent(b.dataset.message)))}
async function loadVolunteers(){const el=$('#volunteersList');if(!el)return;el.innerHTML='<p>Caricamento…</p>';const {data,error}=await db.from('richieste').select('*').in('tipo',volunteerTypes).order('created_at',{ascending:false});if(error){el.innerHTML='<p>Impossibile caricare le candidature.</p>';return}$('#ovVolunteers').textContent=data.length;el.innerHTML=data.length?data.map(r=>`<article class="admin-row"><div><span class="admin-chip">${esc(labels[r.tipo]||r.tipo)}</span><h3>${esc([r.nome,r.cognome].filter(Boolean).join(' ')||r.email||'Candidatura')}</h3><p>${esc(r.email||'')}${r.telefono?' · '+esc(r.telefono):''}</p>${r.regione?`<p>Territorio: ${esc(r.regione)}</p>`:''}<p>${esc(r.oggetto||'')}</p><small>${new Date(r.created_at).toLocaleString('it-IT')}</small></div><div><select data-vol-status="${r.id}">${['nuova','contattato','in_lavorazione','completata','archiviata'].map(x=>`<option ${x===r.stato?'selected':''} value="${x}">${x.replace('_',' ')}</option>`).join('')}</select><button class="admin-detail-vol" data-message="${encodeURIComponent(r.messaggio||'')}">Leggi</button></div></article>`).join(''):'<p>Nessuna candidatura.</p>';document.querySelectorAll('[data-vol-status]').forEach(x=>x.onchange=()=>db.from('richieste').update({stato:x.value}).eq('id',x.dataset.volStatus));document.querySelectorAll('.admin-detail-vol').forEach(b=>b.onclick=()=>showDetail('Candidatura',decodeURIComponent(b.dataset.message)))}
async function loadUsers(){const el=$('#usersList');if(!el)return;el.innerHTML='<p>Caricamento…</p>';const {data,error}=await db.from('profili').select('*').order('created_at',{ascending:false});if(error){
  console.error('ERRORE UTENTI:', error);
  el.innerHTML='<p>Errore Supabase: '+esc(error.message)+'</p>';
  return
}el.innerHTML=data.length?data.map(u=>`<article class="admin-row"><div><span class="admin-chip">${esc(u.piano||'gratis')}</span><h3>${esc([u.nome,u.cognome].filter(Boolean).join(' ')||'Utente')}</h3><p>${esc(u.comune||'')}${u.provincia?' ('+esc(u.provincia)+')':''}</p><small>Stato: ${esc(u.stato||'')} · ${new Date(u.created_at).toLocaleString('it-IT')}</small></div></article>`).join(''):'<p>Nessun utente registrato.</p>'}
async function loadPayments(){
 const el=$('#paymentsList');
 el.innerHTML='<p>Caricamento pagamenti…</p>';
 const {data,error}=await db.from('pagamenti').select('*').order('created_at',{ascending:false});
 if(error){el.innerHTML='<p>Impossibile caricare i pagamenti.</p>';return}
 const rows=data||[];
 const active=rows.filter(p=>String(p.stato||'').toLowerCase()==='attivo');$('#ovPayments').textContent=active.length;
 const monthly=active.reduce((sum,p)=>sum+(String(p.piano||'').toLowerCase()==='mensile'?Number(p.importo||0):0),0);
 const annual=active.reduce((sum,p)=>sum+(String(p.piano||'').toLowerCase()==='annuale'?Number(p.importo||0):0),0);
 const summary=$('#paymentsSummary');
 if(summary) summary.innerHTML=`<div><strong>${rows.length}</strong><span>Registrati</span></div><div><strong>${active.length}</strong><span>Attivi</span></div><div><strong>€ ${monthly.toFixed(2)}</strong><span>Mensili attivi</span></div><div><strong>€ ${annual.toFixed(2)}</strong><span>Annuali attivi</span></div>`;
 const type=$('#paymentTypeFilter')?.value||'tutti', status=$('#paymentStatusFilter')?.value||'tutti';
 const filtered=rows.filter(p=>(type==='tutti'||String(p.tipologia||'').toLowerCase()===type)&&(status==='tutti'||String(p.stato||'').toLowerCase()===status));
 el.innerHTML=filtered.length?filtered.map(p=>{
   const full=[p.nome,p.cognome].filter(Boolean).join(' ');
   const start=p.data_inizio?new Date(p.data_inizio).toLocaleDateString('it-IT'):'—';
   return `<article class="admin-row payment-row"><div><span class="admin-chip">${esc(p.tipologia||'Pagamento')}</span><h3>${esc(full||p.email||'')}</h3>${full&&p.email?`<p class="payment-email">${esc(p.email)}</p>`:''}<p><strong>${esc(p.piano||'')}</strong> ${p.importo?'· € '+Number(p.importo).toFixed(2):''} · ${esc(p.provider||'')}</p><small>Attivazione: ${esc(start)}${p.provider_subscription_id?' · ID: '+esc(p.provider_subscription_id):''}</small></div><strong class="payment-status status-${esc(String(p.stato||'').toLowerCase().replace(/[^a-z0-9_-]/g,''))}">${esc(p.stato||'—')}</strong></article>`;
 }).join(''):'<p>Nessun pagamento con questi filtri.</p>';
}
async function loadGallery(){const el=$('#galleryList');const {data,error}=await db.from('galleria').select('*').order('ordine');if(error){el.innerHTML='<p>Impossibile caricare la galleria.</p>';return}$('#ovGallery').textContent=data.length;el.innerHTML=data.length?data.map(i=>`<article class="admin-photo"><img src="${esc(i.immagine_url)}" alt=""><div><strong>${esc(i.titolo||'Senza titolo')}</strong><small>${esc(i.localita||'')}</small><button data-gallery-delete="${i.id}" data-url="${encodeURIComponent(i.immagine_url)}">Elimina</button></div></article>`).join(''):'<p>Nessuna immagine caricata dal back office.</p>';document.querySelectorAll('[data-gallery-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Eliminare questa immagine?'))return;const url=decodeURIComponent(b.dataset.url);const marker='/storage/v1/object/public/galleria/';const path=url.includes(marker)?url.split(marker)[1]:null;if(path)await db.storage.from('galleria').remove([decodeURIComponent(path)]);await db.from('galleria').delete().eq('id',b.dataset.galleryDelete);loadGallery()})}
$('#galleryForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('#galleryStatus'),file=$('#galleryFile').files[0];if(!file)return;st.textContent='Caricamento…';const path=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await db.storage.from('galleria').upload(path,file,{upsert:false});if(up.error){st.textContent=up.error.message;return}const {data:url}=db.storage.from('galleria').getPublicUrl(path);const {error}=await db.from('galleria').insert({titolo:$('#galleryTitle').value||null,localita:$('#galleryLocation').value||null,descrizione:$('#galleryDescription').value||null,immagine_url:url.publicUrl,alt_text:$('#galleryTitle').value||'Progetto Libri Liberi',pubblicata:$('#galleryPublished').checked});if(error){st.textContent=error.message;return}e.target.reset();$('#galleryPublished').checked=true;st.textContent='Immagine caricata.';loadGallery()});

function selectedCoursePlans(){return [...document.querySelectorAll('input[name="coursePlan"]:checked')].map(x=>x.value)}
function resetCourseForm(){const f=$('#courseForm');f.reset();$('#courseId').value='';$('#coursePublished').checked=true;const sp=document.querySelector('input[name="coursePlan"][value="sponsor"]');if(sp)sp.checked=true;$('#courseCancel').hidden=true;$('#courseStatus').textContent=''}
async function loadCourses(){const el=$('#coursesList');if(!el)return;el.innerHTML='<p>Caricamento corsi…</p>';const {data,error}=await db.from('corsi').select('*').order('created_at',{ascending:false});if(error){el.innerHTML='<p>Errore corsi: '+esc(error.message)+'</p>';return}el.innerHTML=data?.length?data.map(c=>`<article class="admin-row"><div><span class="admin-chip">${esc(c.categoria||'Corso')}</span><h3>${esc(c.titolo)}</h3><p>${esc(c.descrizione||'')}</p><small>Destinatari: ${esc((c.destinatari||[]).join(', '))} · ${c.pubblicato?'Pubblicato':'Bozza'}</small></div><div><button class="admin-detail" data-course-edit="${c.id}">Modifica</button><button class="admin-detail" data-course-delete="${c.id}">Elimina</button></div></article>`).join(''):'<p>Nessun corso.</p>';document.querySelectorAll('[data-course-edit]').forEach(b=>b.onclick=()=>editCourse(b.dataset.courseEdit,data));document.querySelectorAll('[data-course-delete]').forEach(b=>b.onclick=()=>deleteCourse(b.dataset.courseDelete))}
function editCourse(id,rows){const c=rows.find(x=>String(x.id)===String(id));if(!c)return;$('#courseId').value=c.id;$('#courseTitle').value=c.titolo||'';$('#courseDescription').value=c.descrizione||'';$('#courseCategory').value=c.categoria||'';$('#courseImage').value=c.immagine_url||'';$('#courseLink').value=c.link_corso||'';$('#coursePublished').checked=!!c.pubblicato;document.querySelectorAll('input[name="coursePlan"]').forEach(x=>x.checked=(c.destinatari||[]).includes(x.value));$('#courseCancel').hidden=false;$('#courseForm').scrollIntoView({behavior:'smooth'})}
async function deleteCourse(id){if(!confirm('Eliminare questo corso?'))return;const {error}=await db.from('corsi').delete().eq('id',id);if(error){alert(error.message);return}loadCourses()}
$('#courseForm')?.addEventListener('submit',async e=>{e.preventDefault();const st=$('#courseStatus'),plans=selectedCoursePlans();if(!plans.length){st.textContent='Seleziona almeno un destinatario.';return}st.textContent='Salvataggio…';const payload={titolo:$('#courseTitle').value.trim(),descrizione:$('#courseDescription').value.trim()||null,categoria:$('#courseCategory').value.trim()||null,immagine_url:$('#courseImage').value.trim()||null,link_corso:$('#courseLink').value.trim(),destinatari:plans,pubblicato:$('#coursePublished').checked,updated_at:new Date().toISOString()};const id=$('#courseId').value;const q=id?db.from('corsi').update(payload).eq('id',id):db.from('corsi').insert(payload);const {error}=await q;if(error){st.textContent=error.message;return}resetCourseForm();await loadCourses()});
$('#courseCancel')?.addEventListener('click',resetCourseForm);


function resetEventForm(){const f=$('#eventForm');if(!f)return;f.reset();$('#eventId').value='';$('#eventPublished').checked=true;$('#eventCancel').hidden=true;$('#eventStatus').textContent=''}
async function loadEvents(){const el=$('#eventsList');if(!el)return;el.innerHTML='<p>Caricamento eventi…</p>';const {data,error}=await db.from('eventi_partner').select('*').order('data_evento',{ascending:true});if(error){el.innerHTML='<p>Errore eventi: '+esc(error.message)+'</p>';return}el.innerHTML=data?.length?data.map(e=>`<article class="admin-row"><div><span class="admin-chip">${new Date(e.data_evento).toLocaleString('it-IT')}</span><h3>${esc(e.titolo)}</h3><p>${esc(e.luogo||'')}</p><small>${e.pubblicato?'Pubblicato':'Bozza'}</small></div><div><button class="admin-detail" data-event-edit="${e.id}">Modifica</button><button class="admin-detail" data-event-delete="${e.id}">Elimina</button></div></article>`).join(''):'<p>Nessun evento.</p>';document.querySelectorAll('[data-event-edit]').forEach(b=>b.onclick=()=>editEvent(b.dataset.eventEdit,data));document.querySelectorAll('[data-event-delete]').forEach(b=>b.onclick=()=>deleteEvent(b.dataset.eventDelete))}
function editEvent(id,rows){const e=rows.find(x=>String(x.id)===String(id));if(!e)return;$('#eventId').value=e.id;$('#eventTitle').value=e.titolo||'';$('#eventDate').value=String(e.data_evento||'').slice(0,16);$('#eventPlace').value=e.luogo||'';$('#eventImage').value=e.immagine_url||'';$('#eventDescription').value=e.descrizione||'';$('#eventPublished').checked=!!e.pubblicato;$('#eventCancel').hidden=false;$('#eventForm').scrollIntoView({behavior:'smooth'})}
async function deleteEvent(id){if(!confirm('Eliminare questo evento?'))return;const {error}=await db.from('eventi_partner').delete().eq('id',id);if(error){alert(error.message);return}loadEvents()}
$('#eventForm')?.addEventListener('submit',async e=>{e.preventDefault();const st=$('#eventStatus');st.textContent='Salvataggio…';const payload={titolo:$('#eventTitle').value.trim(),descrizione:$('#eventDescription').value.trim()||null,luogo:$('#eventPlace').value.trim()||null,immagine_url:$('#eventImage').value.trim()||null,data_evento:new Date($('#eventDate').value).toISOString(),pubblicato:$('#eventPublished').checked,updated_at:new Date().toISOString()};const id=$('#eventId').value;const q=id?db.from('eventi_partner').update(payload).eq('id',id):db.from('eventi_partner').insert(payload);const {error}=await q;if(error){st.textContent=error.message;return}resetEventForm();loadEvents()});
$('#eventCancel')?.addEventListener('click',resetEventForm);

async function loadEventRequests(){const el=$('#eventRequestsList');if(!el)return;el.innerHTML='<p>Caricamento richieste…</p>';const {data,error}=await db.from('richieste_eventi_partner').select('*,eventi_partner(titolo)').order('created_at',{ascending:false});if(error){el.innerHTML='<p>Errore richieste: '+esc(error.message)+'</p>';return}el.innerHTML=data?.length?data.map(r=>`<article class="admin-row"><div><span class="admin-chip">${esc(r.stato)}</span><h3>${esc(r.eventi_partner?.titolo||'Evento')}</h3><p>${esc(r.nome||'')} ${esc(r.cognome||'')} · ${esc(r.email||'')}</p><small>${new Date(r.created_at).toLocaleString('it-IT')}</small></div><select data-event-request="${r.id}"><option value="nuova"${r.stato==='nuova'?' selected':''}>Nuova</option><option value="contattato"${r.stato==='contattato'?' selected':''}>Contattato</option><option value="confermato"${r.stato==='confermato'?' selected':''}>Confermato</option><option value="rifiutato"${r.stato==='rifiutato'?' selected':''}>Rifiutato</option></select></article>`).join(''):'<p>Nessuna richiesta.</p>';document.querySelectorAll('[data-event-request]').forEach(s=>s.onchange=async()=>{const {error}=await db.from('richieste_eventi_partner').update({stato:s.value,updated_at:new Date().toISOString()}).eq('id',s.dataset.eventRequest);if(error)alert(error.message)})}

document.querySelectorAll('[data-refresh]').forEach(b=>b.onclick=()=>b.dataset.refresh==='richieste'?loadRequests():b.dataset.refresh==='volontari'?loadVolunteers():b.dataset.refresh==='galleria'?loadGallery():b.dataset.refresh==='utenti'?loadUsers():b.dataset.refresh==='corsi'?loadCourses():b.dataset.refresh==='eventi'?loadEvents():b.dataset.refresh==='richieste-eventi'?loadEventRequests():loadPayments());showSession();
$('#paymentTypeFilter')?.addEventListener('change',loadPayments);
$('#paymentStatusFilter')?.addEventListener('change',loadPayments);
